"""индексы по датам отчётов и поставок

Revision ID: a30754777357
Revises: d529baa80695
Create Date: 2026-07-23 10:12:12.362214

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a30754777357"
down_revision: str | Sequence[str] | None = "d529baa80695"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_daily_reports_report_date"), "daily_reports", ["report_date"], unique=False
    )
    op.create_index(
        op.f("ix_material_deliveries_delivery_date"),
        "material_deliveries",
        ["delivery_date"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_material_deliveries_delivery_date"), table_name="material_deliveries")
    op.drop_index(op.f("ix_daily_reports_report_date"), table_name="daily_reports")
    # ### end Alembic commands ###
