"""initial schema

Revision ID: 349f0541606e
Revises:
Create Date: 2026-07-09 12:05:22.020644

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "349f0541606e"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "construction_sites",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("address", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("planned_end_date", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active", "suspended", "completed", name="sitestatus", native_enum=False, length=30
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_construction_sites")),
    )
    op.create_table(
        "materials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_materials")),
        sa.UniqueConstraint("name", name=op.f("uq_materials_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("foreman", "manager", "admin", name="userrole", native_enum=False, length=30),
            nullable=False,
        ),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("password_hash", sa.String(), nullable=True),
        sa.Column("telegram_id", sa.BigInteger(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.UniqueConstraint("telegram_id", name=op.f("uq_users_telegram_id")),
    )
    op.create_table(
        "crews",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.CheckConstraint("size > 0", name=op.f("ck_crews_size_positive")),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["construction_sites.id"],
            name=op.f("fk_crews_site_id_construction_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_crews")),
    )
    op.create_index(op.f("ix_crews_site_id"), "crews", ["site_id"], unique=False)
    op.create_table(
        "daily_reports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("foreman_id", sa.Integer(), nullable=False),
        sa.Column("report_date", sa.Date(), nullable=False),
        sa.Column("work_description", sa.String(), nullable=False),
        sa.Column("workers_count", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "workers_count >= 0", name=op.f("ck_daily_reports_workers_count_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["foreman_id"],
            ["users.id"],
            name=op.f("fk_daily_reports_foreman_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["construction_sites.id"],
            name=op.f("fk_daily_reports_site_id_construction_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_reports")),
        sa.UniqueConstraint(
            "site_id", "foreman_id", "report_date", name="uq_daily_reports_site_foreman_date"
        ),
    )
    op.create_index(
        op.f("ix_daily_reports_foreman_id"), "daily_reports", ["foreman_id"], unique=False
    )
    op.create_table(
        "material_deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.Column("delivery_date", sa.Date(), nullable=False),
        sa.Column("supplier", sa.String(), nullable=False),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_material_deliveries_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_material_deliveries_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["construction_sites.id"],
            name=op.f("fk_material_deliveries_site_id_construction_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_deliveries")),
    )
    op.create_index(
        op.f("ix_material_deliveries_material_id"),
        "material_deliveries",
        ["material_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_material_deliveries_site_id"), "material_deliveries", ["site_id"], unique=False
    )
    op.create_table(
        "site_assignments",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("site_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["construction_sites.id"],
            name=op.f("fk_site_assignments_site_id_construction_sites"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_site_assignments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "site_id", name=op.f("pk_site_assignments")),
    )
    op.create_index(
        op.f("ix_site_assignments_site_id"), "site_assignments", ["site_id"], unique=False
    )
    op.create_table(
        "report_material_usages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("material_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=12, scale=3), nullable=False),
        sa.CheckConstraint(
            "quantity > 0", name=op.f("ck_report_material_usages_quantity_positive")
        ),
        sa.ForeignKeyConstraint(
            ["material_id"],
            ["materials.id"],
            name=op.f("fk_report_material_usages_material_id_materials"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["daily_reports.id"],
            name=op.f("fk_report_material_usages_report_id_daily_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_material_usages")),
        sa.UniqueConstraint(
            "report_id", "material_id", name="uq_report_material_usages_report_material"
        ),
    )
    op.create_index(
        op.f("ix_report_material_usages_material_id"),
        "report_material_usages",
        ["material_id"],
        unique=False,
    )
    op.create_table(
        "report_photos",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_id", sa.Integer(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["daily_reports.id"],
            name=op.f("fk_report_photos_report_id_daily_reports"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_photos")),
    )
    op.create_index(
        op.f("ix_report_photos_report_id"), "report_photos", ["report_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_photos_report_id"), table_name="report_photos")
    op.drop_table("report_photos")
    op.drop_index(
        op.f("ix_report_material_usages_material_id"), table_name="report_material_usages"
    )
    op.drop_table("report_material_usages")
    op.drop_index(op.f("ix_site_assignments_site_id"), table_name="site_assignments")
    op.drop_table("site_assignments")
    op.drop_index(op.f("ix_material_deliveries_site_id"), table_name="material_deliveries")
    op.drop_index(op.f("ix_material_deliveries_material_id"), table_name="material_deliveries")
    op.drop_table("material_deliveries")
    op.drop_index(op.f("ix_daily_reports_foreman_id"), table_name="daily_reports")
    op.drop_table("daily_reports")
    op.drop_index(op.f("ix_crews_site_id"), table_name="crews")
    op.drop_table("crews")
    op.drop_table("users")
    op.drop_table("materials")
    op.drop_table("construction_sites")
    # ### end Alembic commands ###
